services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: library_management_system_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - postgres_network
    ports:
      - "5432:5432"

  rails:
    build:
      context: .
      dockerfile: devops/development/docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/app
    networks:
      - postgres_network
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: library_management_system_development

volumes:
  postgres_data:
networks:
  postgres_network:
