default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library_management_system_development
  username: postgres
  password: password
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

test:
  <<: *default
  database: library_management_system_test

production:
  <<: *default
  database: library_management_system_production
  username: library_management_system
  password: <%= ENV["LIBRARY_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>
